name: Manual Euromillones Scraper

on:
  workflow_dispatch:
    inputs:
      date:
        description: 'Date to execute the scrapper (YYYY-MM-DD)'
        required: true

env:
  PG_HOST: ${{ secrets.PG_HOST }}
  PG_PORT: ${{ secrets.PG_PORT }}
  PG_DB: ${{ secrets.PG_DB }}
  PG_USER: ${{ secrets.PG_USER }}
  PG_PASSWORD: ${{ secrets.PG_PASSWORD }}

jobs:
  manual_scraper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run scraper for manual date
        run: |
          DATE="${{ github.event.inputs.date }}"
          echo "Running scraper for date: $DATE"
          bundle exec ruby scrapper/scrapper.rb $DATE
